apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: container-executor-pytest
spec:
  image: dommgifer/pytest-executor:latest
  executor_type: container
  types:
  - container-executor-pytest/test
